### ISSUE TITLE
Error with base config

### ISSUE THREAD

**Issue by elit3ge** [Vansmak/OCDarr#5]
Still receiving an error with the base config.

```
2024-06-02 12:03:05,387:INFO:Received POST request from Tautulli
2024-06-02 12:03:05,387:INFO:Webhook received with data: {'plex_title': 'Will Trent', 'plex_season_num': '1', 'plex_ep_num': '11'}
2024-06-02 12:03:05,401:INFO:Data successfully written to data_from_tautulli.json
2024-06-02 12:03:05,812:ERROR:Errors from servertosonarr.py: 2024-06-02 12:03:05,728 - DEBUG - Starting new HTTP connection (1): 10.***:30076
2024-06-02 12:03:05,765 - DEBUG - http://10.***:30076 "GET /api/v3/series HTTP/1.1" 200 None
2024-06-02 12:03:05,781 - DEBUG - Starting new HTTP connection (1): 10.38.138.248:30076
2024-06-02 12:03:05,787 - DEBUG - http://10.***:30076 "GET /api/v3/episode?seriesId=245&seasonNumber=1 HTTP/1.1" 200 None
2024-06-02 12:03:05,789 - DEBUG - Starting new HTTP connection (1): 10.3***:30076
2024-06-02 12:03:05,794 - DEBUG - http://10.***:30076 "GET /api/v3/series/245 HTTP/1.1" 200 None
2024-06-02 12:03:05,795 - DEBUG - IDs to unmonitor: [36575, 36576, 36577, 36578, 36579, 36580, 36581, 36582, 36583, 36584, 36585]
Traceback (most recent call last):
  File "/app/servertosonarr.py", line 201, in <module>
    main()
  File "/app/servertosonarr.py", line 181, in main
    episodes_needed = config['get_option'] - len(remaining_current_season)
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

Config
```
{
    "get_option": "2",
    "action_option": "search",
    "keep_watched": "Season",
    "always_keep": [],
    "monitor_watched": true
}
```

**Comment by elit3ge** [comment]
Got another error now.. :\

```
2024-06-02 17:51:47,123:INFO:Received POST request from Tautulli
2024-06-02 17:51:47,123:INFO:Webhook received with data: {'plex_title': "Bob's Burgers", 'plex_season_num': '4', 'plex_ep_num': '22'}
2024-06-02 17:51:47,127:INFO:Data successfully written to data_from_tautulli.json
2024-06-02 17:51:47,473:ERROR:Errors from servertosonarr.py: Traceback (most recent call last):
  File "/app/servertosonarr.py", line 220, in <module>
    main()
  File "/app/servertosonarr.py", line 167, in main
    series_name, season_number, episode_number = get_server_activity("webhook_data.json")
TypeError: get_server_activity() takes 0 positional arguments but 1 was given
```

**Comment by Vansmak** [comment]
How are you running it? From pre built docker or docker build? What
machine?

**Comment by Vansmak** [comment]
i think i had uploaded an incomplete file.
